#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    i=0
    plusCount=0
    minusCount=0

    while i<len(arr):
        if arr[i]<0:
            minusCount+=1
            i+=1
        elif arr[i]>0:
            plusCount+=1
            i+=1
        else:
            i+=1
    zeroCount = len(arr)-minusCount-plusCount

    print(round(plusCount/len(arr),6))
    print(round(minusCount/len(arr),6))
    print(round(zeroCount/len(arr),6))
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
