#!/bin/python3

import os
import sys

#
# Complete the timeConversion function below.
#


def timeConversion(s):

    if s[:2]=='12':
        if s[-2]=='P':
            return s[:-2]
        elif s[-2]=='A':
            newList = list(s)
            newList[:2]=['0','0']
            s=''.join(newList)
            return s[:-2]

    
    if s[-2]=='P':
        hh = int(s[:2])+12
        newList = list(s)
        newList[:2]= list(str(hh))
        s = ''.join(newList)
        return s[:-2]
        
    elif s[-2]=='A':
        return s[:-2]

if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    f.write(result + '\n')

    f.close()
