#!/bin/python

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    minSum = 0
    maxSum = 0
    temp_arr1 = []
    temp_arr2 = []
    i = 0

    while i < len(arr):
        temp_arr1.append(arr[i])
        temp_arr2.append(arr[i])
        i+=1

    for i in range(4):
        minSum +=min(temp_arr1)
        temp_arr1.remove(min(temp_arr1))

        maxSum += max(temp_arr2)
        temp_arr2.remove(max(temp_arr2))

    print minSum, maxSum    

if __name__ == '__main__':
    arr = map(int, raw_input().rstrip().split())

    miniMaxSum(arr)
