#!/bin/python3

import math
import os
import random
import re
import sys

def compareTriplets(alice, bob):
    alice_points = 0
    bob_points = 0
    
    for i in range(3):
        if alice[i]>bob[i]:
            alice_points+=1
        elif alice[i]<bob[i]:
            bob_points+=1
    
    return alice_points, bob_points

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
